export default {
  Root: 'Root',
  AppStack: 'AppStack',
  AuthStack: 'AuthStack',
  HomeStack: 'HomeStack',
  HomeTab: 'HomeTab',
  ProjectTab: 'ProjectTab',
  P2PTab: 'P2PTab',
  DefiTab: 'DefiTab',
  PartnerTab: 'PartnerTab',

  //Screen
  Splash: 'SplashScreen',
  Register: 'Register',
  Login: 'Login',
  VerifySuccessScreen: 'VerifySuccessScreen',
  RegisterOnboardScreen: 'RegisterOnboardScreen',
  HomeScreen: 'HomeScreen',
  CountryScreen: 'CountryScreen',
  SettingScreen: 'SettingScreen',
  LanguageScreen: 'LanguageScreen',
  MyProfileScreen: 'MyProfileScreen',
  UpdateEmailScreen: 'UpdateEmailScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  TouchIDScreen: 'TouchIDScreen',
  IDCardScreen: 'IDCardScreen',
  RecordScreen: 'RecordScreen',
  KYCPendingScreen: 'KYCPendingScreen',
  KYCSuccessScreen: 'KYCSuccessScreen',
  RejectedScreen: 'RejectedScreen',
  DigitalAssetScreen: 'DigitalAssetScreen',
  ReceiveScreen: 'ReceiveScreen',
  ReceiveDigitalScreen: 'ReceiveDigitalScreen',
  DigitalDetailScreen: 'DigitalDetailScreen',
  TransactionHistoryScreen: 'TransactionHistoryScreen',
  SendScreen: 'SendScreen',
  SendDigitalScreen: 'SendDigitalScreen',
  ScanQRCodeScreen: 'ScanQRCodeScreen',
  ToAddressScreen: 'ToAddressScreen',
  ConfirmSendScreen: 'ConfirmSendScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  ResetPasswordScreen: 'ResetPasswordScreen',
  VerifyOTPScreen: 'VerifyOTPScreen',
  P2PTradingScreen: 'P2PTradingScreen',
  P2PUserScreen: 'P2PUserScreen',
  CreateOrderScreen: 'CreateOrderScreen',
  BuySellScreen: 'BuySellScreen',
  ComingSoonScreen: 'ComingSoonScreen',
  MyOrderScreen: 'MyOrderScreen',
  MyOrderDetailScreen: 'MyOrderDetailScreen',
  OrderTransactionScreen: 'OrderTransactionScreen',
  OrderTransactionDetailScreen: 'OrderTransactionDetailScreen',
  DefiScreen: 'DefiScreen',
  HistoryDetailScreen: 'HistoryDetailScreen',

  //KYC
  KYCOnboardingScreen: 'KYCOnboardingScreen',
  PersonalInformationScreen: 'PersonalInformationScreen',
};
